# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucy7isv2hPE67Z3zUg9dcdkw28dhYyXu
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st
from PIL import Image
from utils import predict_tumor

st.set_page_config(page_title="Brain Tumor Classifier", layout="centered")

st.title("🧠 Brain Tumor MRI Classifier")
st.write("Upload a brain MRI image to predict the type of tumor.")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_container_width=True)

    if st.button("Predict"):
        label, confidence = predict_tumor(image)
        st.success(f"### 🎯 Prediction: **{label.upper()}**")
        st.info(f"Confidence: `{confidence * 100:.2f}%`")